---
- name: cleaning sos reports
  hosts: localhost
  gather_facts: true
  become: true


  tasks:
          #- include: roles/unarchive_sos/tasks/main.yml
   - include: roles/cleaner/tasks/main.yml

